### ISSUE TITLE
Create build component

### ISSUE THREAD

**Issue by seanknox** [Azure/kashti#120]
* styling per existing feature 
* static HTML is fine

<img width="714" alt="kashti___build" src="https://user-images.githubusercontent.com/1231630/37262655-c683306a-2561-11e8-9461-3bb406c66b1e.png">

**Comment by seanknox** [comment]
@flynnduism I think this is done, right?

**Comment by flynnduism** [comment]
Yes the component was added in #143, this can be closed.

Will refine the build pages and tidy up the API output in separate story
