### ISSUE TITLE
Build status badge on project page

### ISSUE THREAD

**Issue by seanknox** [Azure/kashti#150]
AC:

- correct build status is displayed (e.g. running, success, failed, unknown) in the row for the build.

<img width="675" alt="kashti" src="https://user-images.githubusercontent.com/1231630/37262591-395a3382-2561-11e8-8146-83c947876743.png">

<img width="598" alt="kashti" src="https://user-images.githubusercontent.com/1231630/37262578-23d8a598-2561-11e8-9334-fe1528fc53ae.png">

 I've started work on that to extract to a badge status component in #144.

**Comment by flynnduism** [comment]
@technosophos this is the state work we discussed, if you can take a look? 💋

**Comment by seanknox** [comment]
@flynnduism if Matt's happy, can we close this via #144?

**Comment by technosophos** [comment]
Did some other PR already fix this issue, @ronan? When I just built, things looked great!

**Comment by seanknox** [comment]
@technosophos yep this is in! closed via #174
