### ISSUE TITLE
Project page: Main content can scroll past the header 

### ISSUE THREAD

**Issue by seanknox** [Azure/kashti#159]
STR:
- Visit a project page
- Open dev console in Chrome or Firefox or zoom in until a scroll bar appears in the main content section

EXPECTED:
- Main content stops before header

ACTUAL:
- Main content doesn't stop before header
![out](https://user-images.githubusercontent.com/1231630/37562054-9f919cee-2a1b-11e8-8f64-0d4f99d84b78.gif)

**Comment by flynnduism** [comment]
Will be fixed via #165.
