### ISSUE TITLE
angular5 branch: README says `ng serve`...

### ISSUE THREAD

**Issue by technosophos** [Azure/kashti#171]
I followed the documentation on the `angular5` branch, and it tells me to do `ng serve`. But that errors out (`zsh: command not found: ng`). I believe the `ng` commands should all be `yarn ng ...`, since that will use the ng in `node_modules/.bin`, right? Or should I install ng globally?

I'm happy to do the doc change.

**Comment by flynnduism** [comment]
Possibly missing `angular-cli` which needs to be [installed](https://github.com/angular/angular-cli#installation) globally
