### ISSUE TITLE
proposed: Simplify icon states and use microcopy for nuance

### ISSUE THREAD

**Issue by flynnduism** [Azure/kashti#175]
Regarding #174, I'm a bit concerned about the way the build state icons are accumulating, and proposing some follow-up edits.

![icon-styles](https://user-images.githubusercontent.com/686194/38026725-2032d842-3285-11e8-8f17-913dd9b895cd.gif)

--  

## CSS Tidy-up

There's small glitches around some of the icons, looks like a light gray background shade got applied behind the icons that should be removed (I'll take care of this).

--  

## Pending vs Running

Updating the `active` state to `running` to better match the statuses in Brigade's API makes sense, however I'm not sure about the visual treatment in the UI. 

![icon-styles-2](https://user-images.githubusercontent.com/686194/38027432-88bfc68e-3287-11e8-9f13-b5d2512c605a.gif)

* use of orange indicates a warning or a caution state (IMO)
* the clock icon isn't a clear distinction between waiting to start / running / finished

Essentially both the `active` and `running` states are saying to the user - **wait**, things are happening. I think the icon styles should be similar, and perhaps it's better to distinguish between the states in some text micro copy in the build metadata, rather than trying to convey these nuances in state via icon choices.

i.e. I propose something like this, to let text distinguish between what kind of 'waiting' is happening:

![icon-styles-3](https://user-images.githubusercontent.com/686194/38027501-c6912e9e-3287-11e8-97be-073bb903a6a6.gif)

 @seanknox, what do you think?

--  

Notes:

* the pace of the spinners would be synced - that gif hurts my brain
* in addition to distinguishing between pending vs running, having text convey state would also improve the unknown (aka missing/expired logs) state, as that icon isn't clear enough on it's own

**Comment by seanknox** [comment]
I'm totally in favor of your approach. 👍
