### ISSUE TITLE
nginx routing rules 404 on anything other than /

### ISSUE THREAD

**Issue by bacongobbler** [Azure/kashti#209]
For example, if I open up kashti using `brig dashboard` then refresh the page using these URLs, I get a 404:

http://localhost:8081/dashboard
http://localhost:8081/projects/brigade-someuniqueid

hitting http://localhost:8081/ works fine however

**Comment by bacongobbler** [comment]
this is with deis/kashti:v0.3.0-rc1 btw

**Comment by disha94** [comment]
Facing the same issue, is this fix planned for next release?

**Comment by sapna-nx** [comment]
@bacongobbler can you create a tag for this fix? It's not fixed in the latest Docker Image.
