### ISSUE TITLE
Minor: "Pending 2017 years ago"

### ISSUE THREAD

**Issue by technosophos** [Azure/kashti#87]
When a build is running, it's date is wrong.

I think this is because Go's zero date is the year 0, while JavaScript's is UNIX epoch.

<img width="1144" alt="screen shot 2017-12-02 at 14 58 54" src="https://user-images.githubusercontent.com/89193/33520107-a502fa4e-d771-11e7-801e-b3c2abfed17b.png">

**Comment by flynnduism** [comment]
I'll update this today.
