### ISSUE TITLE
Add a proxy in the server for the brigade API?

### ISSUE THREAD

**Issue by arschles** [Azure/kashti#99]
Perhaps the brigade/kashti install would be easier if brigade-api didn't need to be exposed on a public IP - and therefore didn't have to be secured - and there would be one fewer server in the brigade/kashti system that needed to be secured & exposed to the outside world

Ref https://github.com/Azure/kashti/issues/11
Ref https://github.com/Azure/kashti/issues/10

**Comment by flynnduism** [comment]
Addressed here [https://github.com/Azure/brigade/pull/551](https://github.com/Azure/brigade/pull/551)
